apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zep9maz4w-python
  janus-idp.io/tekton: zep9maz4w-python
  backstage.io/kubernetes-id: zep9maz4w-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zep9maz4w-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
