apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zep9maz4w-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zep9maz4w-python 
  name: zep9maz4w-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zep9maz4w-python 
